version: '3.7'
services:
  app:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/home/circleci/rails-fargate-sample
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  bundle_cache:
  db_data:
